variables:
  access_token: $(System.AccessToken)

jobs:
- job:
  displayName: 'Linux'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      az --version
      az extension list-available --output table
      az extension add azure-devops
      az devops login --instance $(System.TeamFoundationCollectionUri) --token $(access_token)
    displayName: 'Show AZ details / install devops extension'

- job:
  displayName: 'Windows'
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: |
      az --version
      az extension list-available --output table
    displayName: 'Show AZ details'
