pool:
  vmImage: ubuntu-16.04

variables:
  access_token: $(System.AccessToken)

steps:
  - script: |
      install_script_url='https://vstscli.blob.core.windows.net/install/install.py'
      install_script_path=$(mktemp -t vsts_cli_install_tmp_XXXX)
      curl -# $install_script_url > $install_script_path
      # the script takes 3 inputs via stdin (all can just be ENTER)
      echo $'\n\n\n' | python3 $install_script_path
      # need to update $PATH to include the install directory of the CLI
      echo '##vso[task.prependpath]~/lib/vsts-cli/bin'
    displayName: 'Install VSTS CLI'

  - script: |
      vsts --version
      vsts login --instance $(System.TeamFoundationCollectionUri) --token $(access_token)    
      vsts configure --defaults instance=$(System.TeamFoundationCollectionUri) 
      vsts configure --defaults project=vsts-cli-in-pipelines
      vsts build list
    displayName: 'Run VSTS CLI'
