variables:
  AZURE_DEVOPS_CLI_PAT: $(System.AccessToken)

jobs:
- job:
  displayName: 'Linux'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      echo "PAT: ${AZURE_DEVOPS_CLI_PAT}"
      az --version
      az extension list-available --output table
      az extension add -n azure-devops
      az devops configure --defaults organization=$(System.TeamFoundationCollectionUri) project=$(System.TeamProject) --use-git-aliases yes
      az pipelines build list
      git pr list
    displayName: 'Show AZ details / install devops extension'

- job:
  displayName: 'Windows'
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - bash: |
      echo "${PATH}"
      echo "$(which az)"
      echo "${AZURE_DEVOPS_CLI_PAT}"
  - powershell: |
      az --version
      az extension list-available --output table
      az extension add -n azure-devops
      az devops configure --defaults organization=$(System.TeamFoundationCollectionUri) project=$(System.TeamProject) --use-git-aliases yes
      az pipelines build list
      git pr list
    displayName: 'Show AZ details / install devops extension'
